import { NextRequest, NextResponse } from 'next/server'

// Force dynamic rendering to prevent build-time execution
export const dynamic = 'force-dynamic'

// CALI Sound YouTube Playlist ID
const CALI_SOUND_PLAYLIST_ID = 'OLAK5uy_l0tfLR4zhcKpOxQsqdUzUdmWNphJGO1Uk'

// Check if a video is music-related
function isMusicContent(video: any): boolean {
  const title = (video.snippet?.title || '').toLowerCase()
  const description = (video.snippet?.description || '').toLowerCase()
  const channelTitle = (video.snippet?.channelTitle || '').toLowerCase()
  const videoOwnerChannelTitle = (video.snippet?.videoOwnerChannelTitle || '').toLowerCase()
  const categoryId = video.snippet?.categoryId || ''
  
  // Parse duration for metadata (but don't filter by duration)
  const duration = video.contentDetails?.duration || ''
  let durationSeconds = 0
  if (duration) {
    const match = duration.match(/PT(\d+H)?(\d+M)?(\d+S)?/)
    if (match) {
      const hours = parseInt(match[1] || '0')
      const minutes = parseInt(match[2] || '0')
      const seconds = parseInt(match[3] || '0')
      durationSeconds = hours * 3600 + minutes * 60 + seconds
    }
  }

  // EXCLUDE if title explicitly contains "#shorts" (YouTube Shorts tag)
  if (title.includes('#shorts')) {
    console.log(`[FILTER] Excluding #shorts in title: ${title}`)
    return false
  }

  // EXCLUDE if title contains "short" (case-insensitive, but not "shortly")
  if (title.includes(' short') || title.startsWith('short ') || (title.includes('short') && !title.includes('shortly'))) {
    console.log(`[FILTER] Excluding "short" in title: ${title}`)
    return false
  }

  // EXCLUDE if description contains "#shorts" or "shorts" keyword
  if (description.includes('#shorts') || description.includes('shorts')) {
    console.log(`[FILTER] Excluding #shorts/shorts in description: ${title}`)
    return false
  }

  // Check tags for shorts-related keywords
  const tags = (video.snippet?.tags || []).map((tag: string) => tag.toLowerCase())
  const hasShortsTag = tags.some((tag: string) => 
    tag.includes('short') || tag.includes('shorts') || tag === '#shorts'
  )
  if (hasShortsTag) {
    console.log(`[FILTER] Excluding shorts tag in tags: ${title} (tags: ${tags.join(', ')})`)
    return false
  }

  // Check channel names
  const allChannelNames = [
    channelTitle,
    videoOwnerChannelTitle,
    video.snippet?.channelTitle || '',
    video.snippet?.videoOwnerChannelTitle || '',
  ].map(name => name.toLowerCase().trim())

  // EXCLUDE other Topic channels (auto-generated by YouTube, not CALI Sound's)
  const isOtherTopicChannel = allChannelNames.some(name => {
    const lowerName = name.toLowerCase().trim()
    return lowerName.endsWith(' - topic') && !lowerName.includes('cali sound')
  })
  
  if (isOtherTopicChannel) {
    console.log(`[FILTER] Excluding Topic channel: ${channelTitle || videoOwnerChannelTitle} - ${title}`)
    return false
  }

  // Check channel names FIRST - Only accept "Cali Sound - Topic" channel
  const isCaliSoundTopic = allChannelNames.some(name => 
    name === 'cali sound - topic' || (name.includes('cali sound') && name.includes('topic'))
  )
  
  // STRICT: Only accept if it's from "Cali Sound - Topic" channel
  if (!isCaliSoundTopic) {
    console.log(`[FILTER] Rejecting (not CALI Sound channel): ${title} (Channel: ${channelTitle || videoOwnerChannelTitle})`)
    return false
  }

  // NOW: ACCEPT if Category ID = 10 (Music category)
  if (categoryId === '10') {
    console.log(`[FILTER] Accepting (CALI Sound Topic, Category 10 - Music, ${durationSeconds}s): ${title}`)
    return true
  }

  // If Category ID is not 10, still accept (CALI Sound channel is trusted)
  console.log(`[FILTER] Accepting (CALI Sound Topic, ${durationSeconds}s, Category: ${categoryId}): ${title}`)
  return true

  // Reject everything else
  console.log(`[FILTER] Rejecting: ${title} (Category: ${categoryId}, Duration: ${durationSeconds}s, Channel: ${channelTitle || videoOwnerChannelTitle})`)
  return false
}

// Get songs from CALI Sound YouTube playlist (music only)
export async function GET() {
  try {
    const apiKey = process.env.NEXT_PUBLIC_YOUTUBE_API_KEY

    if (!apiKey) {
      return NextResponse.json(
        {
          error: 'YouTube API key not configured',
          message: 'Please set NEXT_PUBLIC_YOUTUBE_API_KEY in .env.local',
        },
        { status: 500 }
      )
    }

    // Step 1: Get all videos from the playlist
    let allPlaylistItems: any[] = []
    let nextPageToken: string | undefined = undefined

    console.log(`[API] Fetching playlist: ${CALI_SOUND_PLAYLIST_ID}`)

    do {
      const playlistUrl = `https://www.googleapis.com/youtube/v3/playlistItems?part=snippet,contentDetails&playlistId=${CALI_SOUND_PLAYLIST_ID}&maxResults=50&key=${apiKey}${nextPageToken ? `&pageToken=${nextPageToken}` : ''}`
      
      console.log(`[API] Requesting: ${playlistUrl.substring(0, 100)}...`)
      
      const playlistResponse = await fetch(playlistUrl)
      const responseText = await playlistResponse.text()
      
      if (!playlistResponse.ok) {
        console.error('[API] YouTube playlist error:', responseText)
        let errorDetails
        try {
          errorDetails = JSON.parse(responseText)
        } catch {
          errorDetails = { message: responseText }
        }
        
        return NextResponse.json(
          { 
            error: 'Failed to get playlist items', 
            details: errorDetails,
            playlistId: CALI_SOUND_PLAYLIST_ID,
            status: playlistResponse.status,
            message: `YouTube API hatası: ${errorDetails.error?.message || responseText}`
          },
          { status: playlistResponse.status }
        )
      }

      let playlistData
      try {
        playlistData = JSON.parse(responseText)
      } catch (e) {
        console.error('[API] Failed to parse response:', e)
        return NextResponse.json(
          { 
            error: 'Invalid response from YouTube API',
            playlistId: CALI_SOUND_PLAYLIST_ID,
            message: 'YouTube API\'den geçersiz yanıt alındı'
          },
          { status: 500 }
        )
      }

      console.log(`[API] Received ${playlistData.items?.length || 0} items in this page`)
      allPlaylistItems = [...allPlaylistItems, ...(playlistData.items || [])]
      nextPageToken = playlistData.nextPageToken
    } while (nextPageToken)

    console.log(`[API] Found ${allPlaylistItems.length} items in playlist ${CALI_SOUND_PLAYLIST_ID}`)
    
    if (allPlaylistItems.length === 0) {
      return NextResponse.json(
        { 
          error: 'No items found in playlist', 
          playlistId: CALI_SOUND_PLAYLIST_ID,
          message: 'Playlist boş veya erişilemiyor. Lütfen playlist ID\'yi kontrol edin.'
        },
        { status: 404 }
      )
    }

    // Step 2: Get video details (duration, category, etc.) for all videos
    const videoIds = allPlaylistItems
      .map((item: any) => item.contentDetails?.videoId || item.snippet?.resourceId?.videoId)
      .filter((id: string) => id)
      .join(',')

    let videoDetails: any = {}
    if (videoIds) {
      // YouTube API allows max 50 IDs per request, so we might need to batch
      const videoIdArray = videoIds.split(',')
      const batches = []
      for (let i = 0; i < videoIdArray.length; i += 50) {
        batches.push(videoIdArray.slice(i, i + 50))
      }

      for (const batch of batches) {
        const batchIds = batch.join(',')
        // Get more details including tags and language
        const detailsUrl = `https://www.googleapis.com/youtube/v3/videos?part=contentDetails,snippet,statistics&id=${batchIds}&key=${apiKey}`
        const detailsResponse = await fetch(detailsUrl)
        
        if (detailsResponse.ok) {
          const detailsData = await detailsResponse.json()
          ;(detailsData.items || []).forEach((item: any) => {
            videoDetails[item.id] = item
          })
        }
      }
    }

    // Step 3: Merge playlist items with video details and filter for music only
    const mergedItems = allPlaylistItems
      .map((item: any) => {
        const videoId = item.contentDetails?.videoId || item.snippet?.resourceId?.videoId
        if (!videoId) return null

        const details = videoDetails[videoId] || {}
        
        // Merge playlist item with video details
        return {
          ...item,
          snippet: {
            ...item.snippet,
            ...details.snippet,
          },
          contentDetails: {
            ...item.contentDetails,
            ...details.contentDetails,
          },
        }
      })
      .filter((item: any) => item !== null)

    console.log(`[API] Total items after merge: ${mergedItems.length}`)

    // Filter for music content using smart filtering
    const musicVideos = mergedItems.filter((item: any) => isMusicContent(item))

    console.log(`[API] After filtering: ${musicVideos.length} music videos (from ${allPlaylistItems.length} total items)`)
    
    // NO FALLBACK - Strict filtering only
    if (musicVideos.length === 0) {
      console.warn(`[API] No music videos after strict filtering. Returning empty list.`)
      return NextResponse.json({
        songs: [],
        count: 0,
        totalItems: allPlaylistItems.length,
        filteredOut: allPlaylistItems.length,
        playlistId: CALI_SOUND_PLAYLIST_ID,
        message: 'No music videos found after filtering. Only CALI Sound - Topic channel videos with 2-6 minute duration are accepted.'
      })
    }
    
    // Format results

    // Step 4: Format results with detailed metadata for filtering analysis
    const formattedSongs = musicVideos
      .map((item: any) => {
        const videoId = item.contentDetails?.videoId || item.snippet?.resourceId?.videoId
        const snippet = item.snippet || {}
        
        // Parse duration (ISO 8601 format: PT4M13S)
        let durationSeconds = 0
        if (item.contentDetails?.duration) {
          const durationMatch = item.contentDetails.duration.match(/PT(\d+H)?(\d+M)?(\d+S)?/)
          if (durationMatch) {
            const hours = parseInt(durationMatch[1] || '0')
            const minutes = parseInt(durationMatch[2] || '0')
            const seconds = parseInt(durationMatch[3] || '0')
            durationSeconds = hours * 3600 + minutes * 60 + seconds
          }
        }

        const artist = snippet.videoOwnerChannelTitle || snippet.channelTitle || 'CALI Sound'
        const channelName = snippet.channelTitle || 'UNKNOWN'
        const videoOwnerChannel = snippet.videoOwnerChannelTitle || 'UNKNOWN'
        const categoryId = snippet.categoryId || null
        const tags = snippet.tags || []
        const title = snippet.title || 'Untitled'
        const titleLower = title.toLowerCase()

        return {
          id: videoId,
          title: title,
          artist: artist,
          description: snippet.description || '',
          thumbnail: snippet.thumbnails?.high?.url || snippet.thumbnails?.medium?.url,
          publishedAt: snippet.publishedAt,
          duration: durationSeconds,
          youtube_url: `https://www.youtube.com/watch?v=${videoId}`,
          embed_url: `https://www.youtube.com/embed/${videoId}`,
          // Metadata for filtering analysis
          _metadata: {
            categoryId: categoryId, // 10 = Music
            channelTitle: channelName,
            videoOwnerChannelTitle: videoOwnerChannel,
            tags: tags,
            hasShortsTag: titleLower.includes('#shorts'),
            isTopicChannel: channelName.toLowerCase().endsWith(' - topic') || videoOwnerChannel.toLowerCase().endsWith(' - topic'),
            durationSeconds: durationSeconds,
            defaultAudioLanguage: snippet.defaultAudioLanguage || null,
            defaultLanguage: snippet.defaultLanguage || null,
          }
        }
      })
      .filter((song: any) => {
        // FIRST: Only accept "Cali Sound - Topic" channel
        const channelName = (song._metadata?.channelTitle || song._metadata?.videoOwnerChannelTitle || '').toLowerCase()
        const isCaliSoundTopic = channelName === 'cali sound - topic' || 
                                 (channelName.includes('cali sound') && channelName.includes('topic'))
        
        if (!isCaliSoundTopic) {
          console.log(`[FINAL FILTER] Excluding (not CALI Sound channel): ${song.title} (Channel: ${song._metadata?.channelTitle || song._metadata?.videoOwnerChannelTitle})`)
          return false
        }

        // EXCLUDE if title contains "#shorts" or "short"
        const titleLower = (song.title || '').toLowerCase()
        if (titleLower.includes('#shorts') || (titleLower.includes(' short') || titleLower.startsWith('short '))) {
          console.log(`[FINAL FILTER] Excluding (contains "short"): ${song.title}`)
          return false
        }
        
        // EXCLUDE if description contains "#shorts" or "shorts"
        const description = (song.description || '').toLowerCase()
        if (description.includes('#shorts') || description.includes('shorts')) {
          console.log(`[FINAL FILTER] Excluding (shorts in description): ${song.title}`)
          return false
        }
        
        // EXCLUDE if tags contain shorts-related keywords
        const tags = (song._metadata?.tags || []).map((tag: string) => tag.toLowerCase())
        const hasShortsTag = tags.some((tag: string) => 
          tag.includes('short') || tag.includes('shorts') || tag === '#shorts'
        )
        if (hasShortsTag) {
          console.log(`[FINAL FILTER] Excluding (shorts tag): ${song.title}`)
          return false
        }

        // ACCEPT if it passed all filters (already filtered by isMusicContent)
        return true
      })

    return NextResponse.json({ 
      songs: formattedSongs,
      count: formattedSongs.length,
      totalItems: allPlaylistItems.length,
      filteredOut: allPlaylistItems.length - formattedSongs.length,
      playlistId: CALI_SOUND_PLAYLIST_ID
    })
  } catch (error: any) {
    console.error('Error getting CALI Sound playlist songs:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}
